parameters:
 #    stuart_hashtag.example.class: Stuart\HashtagBundle\Example
 
 services:
 #    stuart_hashtag.example:
 #        class: %stuart_hashtag.example.class%
 #        arguments: [@service_id, "plain_value", %parameter%]